---

- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Import YARN APT key
  apt_key:
    url: "{{ yarn_debian_repo_gpg_key_url }}"
    state: present

- name: Install YARN APT repo
  apt_repository:
    repo: "deb {{ yarn_debian_repo_url }}"
    filename: "yarn"
    state: present
    update_cache: yes

- name: Install YARN package manager
  package: name=yarn state=latest

# - name: "Yarn | De-configure shell profiles"
#   lineinfile:
#     dest: "ubuntu/{{ item }}"
#     regexp: "PATH:{{ yarn_global_path }}/bin"
#     line:  'export PATH="$PATH:/usr/local/bin";'
#     state: present
#   failed_when: false
#   with_items:
#     - "{{ yarn_shell_profiles }}"

# - name: Update all packages in package.json to their latest version.
#   yarn:
#     path: /var/www
#     state: latest

